# Generated by Django 3.1.4 on 2021-04-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_img', models.ImageField(upload_to='')),
                ('student_name', models.TextField(default='', max_length=20)),
                ('enrollment_no', models.IntegerField(default=0)),
                ('gender', models.TextField(default='', max_length=10)),
                ('hobby', models.CharField(default='', max_length=50)),
                ('country', models.TextField(default='', max_length=10)),
                ('city', models.TextField(default='', max_length=10)),
                ('state', models.TextField(default='', max_length=10)),
            ],
        ),
    ]
